#!/usr/bin/python
# -*- coding: utf-8 -*-

'''
https://projecteuler.net/problem=44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

= 5482660
'''

import time
import math
import sys
from euler import *

start_time = time.clock()
''' '''


pentagonal = set([1, 5, 12, 22, 35, 51, 70, 92, 117, 145])
d_set = set()
for n in range(11, 3000):
    p = n * (3 * n - 1) / 2
    pentagonal.add(p)

    for j in pentagonal:
        if j > p:
            break
        if p - j in pentagonal:
            k = p - j
            if abs(k - j) in pentagonal:
                d_set.add(abs(k - j))

print min(d_set)






# '''
print time.clock() - start_time


